name: flutter_google_map_sal
description: Google places autocomplete widgets for flutter. No wrapper, use https://pub.dartlang.org/packages/google_maps_webservice.
version: 0.0.1
homepage: https://github.com/ishalsaja/flutter_google_map_sal
repository: https://github.com/ishalsaja/flutter_google_map_sal

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  google_api_headers: ^1.1.1
  google_maps_webservice: ^0.0.19
  http: ^0.13.4
  rxdart: ^0.27.3
  rxdart_ext: ^0.1.3
  listenable_stream: ^1.1.0
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  